spring.application.name=SpringSec
spring.security.user.name=siddharth
spring.security.user.password=shukla
spring.datasource.url=jdbc:mysql://localhost:3306/springsecurity
spring.datasource.username=root
spring.datasource.password=1234
jwt.secret=mysecretkeymysecretkeymysecretkey12345
jwt.expiration=36000000
